#!/usr/bin/env python3
"""
Create Maxwell's Equations PDF

This script generates a professionally formatted PDF document with properly rendered
Maxwell's Equations for the Theory of Everything project.
"""

import os
from augmentic_pdf_agent import PDFAgent

def create_maxwell_equations_pdf():
    """Create a PDF document with Maxwell's Equations"""
    # Create output directory
    output_dir = "/home/codephreak/theoryofeverything/theoryofeverything/docs/pdf/formulas"
    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, "Maxwell_Equations_Enhanced.pdf")
    
    # Create PDF agent with specific output directory
    agent = PDFAgent(output_dir="/home/codephreak/theoryofeverything/theoryofeverything/gfx/pdf")
    
    # Define the content for the PDF
    content = {
        "title": "Maxwell's Equations",
        "subtitle": "Fundamental Equations of Electromagnetism",
        "sections": [
            {
                "title": "Introduction",
                "text": (
                    "Maxwell's equations are a set of four partial differential equations that form the foundation "
                    "of classical electromagnetism, classical optics, and electric circuits. These equations describe "
                    "how electric and magnetic fields are generated by charges, currents, and changes of each other. "
                    "They were first presented by James Clerk Maxwell in 1861 and 1862."
                )
            },
            {
                "title": "Differential Form",
                "text": (
                    "In differential form, Maxwell's equations can be written as follows:"
                ),
                "subsections": [
                    {
                        "title": "Gauss's Law for Electricity",
                        "formula": {
                            "name": "Gauss's Law for Electricity",
                            "equation": r"\nabla \cdot \vec{E} = \frac{\rho}{\varepsilon_0}",
                            "description": "Where ∇·E⃗ is the divergence of the electric field, ρ is the electric charge density, and ε₀ is the permittivity of free space. This equation relates the electric field to the distribution of electric charges."
                        }
                    },
                    {
                        "title": "Gauss's Law for Magnetism",
                        "formula": {
                            "name": "Gauss's Law for Magnetism",
                            "equation": r"\nabla \cdot \vec{B} = 0",
                            "description": "Where ∇·B⃗ is the divergence of the magnetic field. This equation states that there are no magnetic monopoles; the magnetic field lines always form closed loops."
                        }
                    },
                    {
                        "title": "Faraday's Law of Induction",
                        "formula": {
                            "name": "Faraday's Law of Induction",
                            "equation": r"\nabla \times \vec{E} = -\frac{\partial \vec{B}}{\partial t}",
                            "description": "Where ∇×E⃗ is the curl of the electric field and ∂B⃗/∂t is the rate of change of the magnetic field with time. This equation describes how a changing magnetic field induces an electric field."
                        }
                    },
                    {
                        "title": "Ampère's Law with Maxwell's Addition",
                        "formula": {
                            "name": "Ampère's Law with Maxwell's Addition",
                            "equation": r"\nabla \times \vec{B} = \mu_0 \vec{J} + \mu_0 \varepsilon_0 \frac{\partial \vec{E}}{\partial t}",
                            "description": "Where ∇×B⃗ is the curl of the magnetic field, J⃗ is the current density, μ₀ is the permeability of free space, and ∂E⃗/∂t is the rate of change of the electric field with time. This equation describes how electric currents and changing electric fields produce magnetic fields."
                        }
                    }
                ]
            },
            {
                "title": "Integral Form",
                "text": (
                    "Maxwell's equations can also be expressed in integral form, which relates the fields "
                    "within a region to the behavior of the fields on the boundary of that region:"
                ),
                "subsections": [
                    {
                        "title": "Gauss's Law for Electricity (Integral Form)",
                        "formula": {
                            "name": "Gauss's Law for Electricity (Integral Form)",
                            "equation": r"\oint_S \vec{E} \cdot d\vec{A} = \frac{Q_{enc}}{\varepsilon_0}",
                            "description": "Where the left side is the electric flux through a closed surface S, and Q_enc is the total charge enclosed by the surface."
                        }
                    },
                    {
                        "title": "Gauss's Law for Magnetism (Integral Form)",
                        "formula": {
                            "name": "Gauss's Law for Magnetism (Integral Form)",
                            "equation": r"\oint_S \vec{B} \cdot d\vec{A} = 0",
                            "description": "Where the left side is the magnetic flux through a closed surface S. This equation states that the net magnetic flux through any closed surface is zero."
                        }
                    },
                    {
                        "title": "Faraday's Law of Induction (Integral Form)",
                        "formula": {
                            "name": "Faraday's Law of Induction (Integral Form)",
                            "equation": r"\oint_C \vec{E} \cdot d\vec{l} = -\frac{d}{dt}\int_S \vec{B} \cdot d\vec{A}",
                            "description": "Where the left side is the electromotive force (EMF) around a closed loop C, and the right side is the rate of change of the magnetic flux through the surface S bounded by the loop."
                        }
                    },
                    {
                        "title": "Ampère's Law with Maxwell's Addition (Integral Form)",
                        "formula": {
                            "name": "Ampère's Law with Maxwell's Addition (Integral Form)",
                            "equation": r"\oint_C \vec{B} \cdot d\vec{l} = \mu_0 I_{enc} + \mu_0 \varepsilon_0 \frac{d}{dt}\int_S \vec{E} \cdot d\vec{A}",
                            "description": "Where the left side is the magnetic field integrated around a closed loop C, I_enc is the current passing through the surface S bounded by the loop, and the last term is the rate of change of the electric flux through the surface."
                        }
                    }
                ]
            },
            {
                "title": "Maxwell's Equations in Vacuum",
                "text": (
                    "In vacuum, where there are no charges (ρ = 0) and no currents (J⃗ = 0), Maxwell's equations simplify to:"
                ),
                "formula": {
                    "name": "Maxwell's Equations in Vacuum",
                    "equation": r"\begin{align} \nabla \cdot \vec{E} &= 0 \\ \nabla \cdot \vec{B} &= 0 \\ \nabla \times \vec{E} &= -\frac{\partial \vec{B}}{\partial t} \\ \nabla \times \vec{B} &= \mu_0 \varepsilon_0 \frac{\partial \vec{E}}{\partial t} \end{align}",
                    "description": "These equations lead to the wave equation for electromagnetic waves, demonstrating that light is an electromagnetic wave with speed c = 1/√(μ₀ε₀)."
                }
            },
            {
                "title": "Electromagnetic Wave Equation",
                "text": (
                    "From Maxwell's equations, we can derive the electromagnetic wave equation:"
                ),
                "formula": {
                    "name": "Electromagnetic Wave Equation",
                    "equation": r"\nabla^2 \vec{E} = \mu_0 \varepsilon_0 \frac{\partial^2 \vec{E}}{\partial t^2}",
                    "description": "This is a second-order partial differential equation that describes the propagation of electromagnetic waves through space. A similar equation can be derived for the magnetic field B⃗."
                }
            },
            {
                "title": "Speed of Light",
                "text": (
                    "One of the most profound consequences of Maxwell's equations is that they predict the existence "
                    "of electromagnetic waves that propagate at a speed given by:"
                ),
                "formula": {
                    "name": "Speed of Light",
                    "equation": r"c = \frac{1}{\sqrt{\mu_0 \varepsilon_0}}",
                    "description": "This speed is approximately 3 × 10⁸ meters per second, which is the speed of light in vacuum. Maxwell's prediction that light is an electromagnetic wave was later confirmed experimentally by Heinrich Hertz."
                }
            },
            {
                "title": "Significance in the Theory of Everything",
                "text": (
                    "Maxwell's equations represent one of the first successful unifications in physics, combining "
                    "electricity and magnetism into a single theory of electromagnetism. This unification serves "
                    "as a model for the Theory of Everything, which aims to unify all fundamental forces. "
                    "In the context of the Theory of Everything, Maxwell's equations are incorporated into the "
                    "broader framework of quantum field theory and gauge theories, particularly through the "
                    "electroweak unification and ultimately in the grand unified theories and beyond."
                )
            }
        ]
    }
    
    # Generate the PDF
    pdf_path = agent.create_scientific_document(
        content["title"],
        content,
        output_file
    )
    
    if pdf_path:
        print(f"Maxwell's Equations PDF created: {pdf_path}")
        return pdf_path
    else:
        print("Failed to create Maxwell's Equations PDF")
        return None

if __name__ == "__main__":
    create_maxwell_equations_pdf()
