#!/usr/bin/env python3
"""
Generate a coherent PDF for Maxwell's Equations with proper formatting
"""

import os
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

def main():
    """Generate a coherent PDF for Maxwell's Equations"""
    # Create the docs/pdf directory if it doesn't exist
    os.makedirs("docs/pdf", exist_ok=True)
    
    # Define the output file
    output_file = "docs/pdf/maxwell.pdf"
    
    # Create a PDF document
    doc = SimpleDocTemplate(output_file, pagesize=letter)
    
    # Define styles
    styles = getSampleStyleSheet()
    
    # Create custom styles
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Title'],
        fontSize=18,
        leading=22,
        alignment=TA_CENTER,
        spaceAfter=20
    )
    
    heading_style = ParagraphStyle(
        'Heading',
        parent=styles['Heading2'],
        fontSize=14,
        leading=18,
        spaceBefore=12,
        spaceAfter=6
    )
    
    normal_style = ParagraphStyle(
        'Normal',
        parent=styles['Normal'],
        fontSize=11,
        leading=14,
        alignment=TA_JUSTIFY
    )
    
    equation_style = ParagraphStyle(
        'Equation',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        alignment=TA_CENTER,
        spaceBefore=8,
        spaceAfter=8
    )
    
    # Maxwell's Equations
    maxwell_equations = [
        {
            "name": "Gauss's Law for Electricity",
            "equation": "∇·E = ρ/ε₀",
            "description": "The electric field diverges from electric charges."
        },
        {
            "name": "Gauss's Law for Magnetism",
            "equation": "∇·B = 0",
            "description": "Magnetic field lines form closed loops; there are no magnetic monopoles."
        },
        {
            "name": "Faraday's Law of Induction",
            "equation": "∇×E = -∂B/∂t",
            "description": "A changing magnetic field creates an electric field."
        },
        {
            "name": "Ampère's Law with Maxwell's Addition",
            "equation": "∇×B = μ₀J + μ₀ε₀∂E/∂t",
            "description": "Electric currents and changing electric fields create magnetic fields."
        }
    ]
    
    # Build the document
    elements = []
    
    # Add title
    elements.append(Paragraph("Maxwell's Equations", title_style))
    elements.append(Spacer(1, 10))
    
    # Add introduction
    elements.append(Paragraph("Introduction", heading_style))
    elements.append(Paragraph(
        "Maxwell's equations are a set of four partial differential equations that form the foundation of "
        "classical electromagnetism, classical optics, and electric circuits. These equations describe how "
        "electric and magnetic fields are generated by charges, currents, and changes of each other. "
        "They were first published by James Clerk Maxwell between 1861 and 1862.", normal_style))
    elements.append(Spacer(1, 10))
    
    # Add equations
    elements.append(Paragraph("The Four Equations", heading_style))
    
    for eq in maxwell_equations:
        elements.append(Paragraph(eq["name"] + ":", heading_style))
        elements.append(Paragraph(eq["equation"], equation_style))
        elements.append(Paragraph(eq["description"], normal_style))
        elements.append(Spacer(1, 8))
    
    # Add implications
    elements.append(Paragraph("Implications", heading_style))
    elements.append(Paragraph(
        "Maxwell's equations have profound implications for our understanding of electromagnetism and light:", normal_style))
    elements.append(Spacer(1, 6))
    
    elements.append(Paragraph("1. Electromagnetic Waves", heading_style))
    elements.append(Paragraph(
        "Maxwell's equations predict the existence of electromagnetic waves that propagate at the speed of light. "
        "This led to the understanding that light itself is an electromagnetic wave.", normal_style))
    elements.append(Spacer(1, 6))
    
    elements.append(Paragraph("2. Speed of Light", heading_style))
    elements.append(Paragraph(
        "The speed of electromagnetic waves in vacuum can be derived from Maxwell's equations as c = 1/√(ε₀μ₀), "
        "which is approximately 3 × 10⁸ m/s.", normal_style))
    elements.append(Spacer(1, 6))
    
    elements.append(Paragraph("3. Electromagnetic Spectrum", heading_style))
    elements.append(Paragraph(
        "Maxwell's equations apply to all electromagnetic waves, from radio waves to gamma rays, "
        "differing only in frequency and wavelength.", normal_style))
    elements.append(Spacer(1, 6))
    
    elements.append(Paragraph("4. Technological Applications", heading_style))
    elements.append(Paragraph(
        "Maxwell's equations form the foundation for numerous technologies, including radio, television, "
        "radar, wireless communications, and optical fiber communications.", normal_style))
    
    # Build the PDF
    try:
        doc.build(elements)
        print(f"Maxwell's Equations PDF saved to: {output_file}")
        print(f"File size: {os.path.getsize(output_file)} bytes")
    except Exception as e:
        print(f"Error generating PDF: {str(e)}")

if __name__ == "__main__":
    main()
